SDS011:
  dataset: rpi
  table_name: pm-sensor
  data:
    - pm2_5
    - pm10
    - loc
    - Date

WS1361-decibel-meter:
  dataset: rpi
  table_name: db-sensor
  data:
    - db
    - r
    - w
    - s
    - l
    - Date